#!ansible-playbook -vv
## sudo-nopassword.tasks.yml
## Configure sudoers so wheel group does not need to enter password.
---
- name: 'passwordless sudo for wheel group'
  block:
    ## https://stackoverflow.com/questions/37333305/ansible-create-a-user-with-sudo-privileges
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^#\s*%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        backup: true

- name: 'Sudo comfort tweaks'
  block:
    - name: 'Sudo: PWFEEDBACK'
      ansible.builtin.lineinfile: # Make password length visible as '*' characters
        dest: /etc/sudoers
        state: present
        regexp: '^Defaults\s+pwfeedback$'
        line: 'Defaults    pwfeedback'
        insertafter: 'Defaults\s+env_reset' # After the environment is reset.
        validate: 'visudo -cf %s'

    - name: 'Sudo: timeout'
      ansible.builtin.lineinfile: # Change timeout period (in minutes)
        dest: /etc/sudoers
        state: present
        regexp: '^Defaults\s+timestamp_timeout=\d+$'
        line: 'Defaults    timestamp_timeout=60' # In minutes.
        insertafter: 'Defaults\s+env_reset' # After the environment is reset.
        validate: 'visudo -cf %s'
