## /etc/seaweedfs/security.toml

# Put this file to one of the location, with descending priority
#    ./security.toml
#    $HOME/.seaweedfs/security.toml
#    /etc/seaweedfs/security.toml
# this file is read by master, volume server, and filer

# the jwt signing key is read by master and volume server.
# a jwt defaults to expire after 10 seconds.
# [jwt.signing]
# key = "this_is_only_a_test"
# expires_after_seconds = 30           # seconds

# jwt for read is only supported with master+volume setup. Filer does not support this mode.
# [jwt.signing.read]
# key = ""
# expires_after_seconds = 10           # seconds

# all grpc tls authentications are mutual
# the values for the following ca, cert, and key are paths to the PERM files.
# the host name is not checked, so the PERM files can be shared.
# [grpc]
# ca = "/etc/seaweedfs/SeaweedFS_CA.crt"

# [grpc.volume]
# cert = "/etc/seaweedfs/volume.crt"
# key  = "/etc/seaweedfs/volume.key"

# [grpc.master]
# cert = "/etc/seaweedfs/master.crt"
# key  = "/etc/seaweedfs/master.key"

# [grpc.filer]
# cert = "/etc/seaweedfs/filer.crt"
# key  = "/etc/seaweedfs/filer.key"

# [grpc.msg_broker]
# cert = "/etc/seaweedfs/"
# key  = "/etc/seaweedfs/"

# use this for any place needs a grpc client
# i.e., "weed backup|benchmark|filer.copy|filer.replicate|mount|s3|upload"
# [grpc.client]
# cert = "/etc/seaweedfs/client.crt"
# key  = "/etc/seaweedfs/client.key"


# volume server https options
# Note: work in progress!
#     this does not work with other clients, e.g., "weed filer|mount" etc, yet.
# [https.client]
# enabled = true
# [https.volume]
# cert = ""
# key  = ""
## Ctrl-S TODO: Figure out how to do TLS/HTTPS!


